# Welcome to Jekyll!

# Website settings
title: "Chuck"
description: "Chuck's blog,use Jekyll and github pages."
keywords: "Chuck,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://www.weiweick.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Chuck'
  first_name: 'chen'
  last_name: 'kai'
  email: 'hgchenkai437@gmail.com'
  facebook_username: 'chucklw'
  github_username: 'hgchenkai'
  head_img: 'static/img/landing/icon.jpg'
  desc: 'I am an Android developer,and I am  eager to learn new  challenging knowledge.Hoping to communicate and share  good ideas with each other.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'
    
  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'
    
 # - id: 'skills'
  #  i18n: 'nav.skills'
   # name: 'Skills'
    #tpl: 'skills.html'
    #css: 'team'

 # - id: 'projects'
 #   i18n: 'nav.projects'
 #   name: 'Projects'
 #   tpl: 'projects.html'
 #   css: 'project'



  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.weiweick.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
disqus:
#  name: chuck
#  public_key: 
duoshuo:
# share
bshare:
  uuid: 3388a8e1-75a8-4d5f-9b83-552bfba42fd1

# baidu analytics
ba:
  uuid: 5452f458cd7817ced78b5c6daa1a82e4

# google analytics
ga:
#  id: 

# growingIO
gio:
#  id: 

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
 